services:
  - type: web
    name: financeflow-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "flask db upgrade && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app
